services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
            - /var/www/vendor # Prevent overwriting vendor folder
            - /var/www/node_modules # Prevent overwriting node_modules folder
        ports:
            - "8000:8000" # Laravel backend
            - "5173:5173" # Vite dev server
        command: >
            sh -c "
              if ! grep -q 'APP_KEY=base64:' .env; then php artisan key:generate; fi &&
              echo 'Waiting for database to be ready...' &&
              timeout 60 sh -c 'until nc -z db 3306; do sleep 1; done' &&
              sleep 5 &&
              php artisan migrate &&
              ( php artisan serve --host=0.0.0.0 --port=8000 & ) &&
              npx vite --host=0.0.0.0 # Start Vite dev server
            "
        depends_on:
            db:
                condition: service_healthy

    db:
        image: mysql:8
        container_name: laravel_db
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u",
                    "laravel",
                    "-psecret",
                    "--silent",
                ]
            interval: 5s
            timeout: 10s
            retries: 10
            start_period: 30s

volumes:
    dbdata:
