services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "8000:8000" # Laravel backend
            - "5173:5173" # Vite dev server
        command: >
            sh -c "
              composer install &&
              if ! grep -q 'APP_KEY=base64:' .env; then php artisan key:generate; fi &&
              npm install &&
              php artisan migrate &&
              (php artisan serve --host=0.0.0.0 --port=8000 &) &&
              npm run dev
            "
        depends_on:
            - db

    db:
        image: mysql:8
        container_name: laravel_db
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
